kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-fs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-disk-hdd-disk
  resources:
    requests:
      storage: 1Gi