kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-disk-pvc
spec:
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  storageClassName: local-disk-hdd-disk
  resources:
    requests:
      storage: 5Gi