apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-disk-hdd-disk
provisioner: disk.hwameistor.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
reclaimPolicy: Delete
parameters:
  diskType: "HDD"
